# Generated by Django 3.1.4 on 2021-11-07 19:08

import django.core.validators
from django.db import migrations, models
import django.utils.crypto
import functools


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0009_stream'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stream',
            name='key',
            field=models.CharField(default=functools.partial(django.utils.crypto.get_random_string, *(20,), **{}), max_length=20, unique=True, validators=[django.core.validators.MinLengthValidator(4)]),
        ),
    ]
