# Generated by Django 3.1.4 on 2021-11-08 17:33

from django.db import migrations, models
import django.utils.crypto
import functools


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0010_auto_20211107_1908'),
    ]

    operations = [
        migrations.AddField(
            model_name='stream',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/streams'),
        ),
        migrations.AddField(
            model_name='stream',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='stream',
            name='key',
            field=models.CharField(default=functools.partial(django.utils.crypto.get_random_string, *(20,), **{}), max_length=20, unique=True),
        ),
    ]
