# Generated by Django 3.1.4 on 2021-11-13 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0011_auto_20211108_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='stream',
            name='category',
            field=models.ManyToManyField(blank=True, null=True, to='recipe.Category'),
        ),
    ]
