# Generated by Django 3.1.4 on 2021-11-13 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0012_stream_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stream',
            name='category',
            field=models.ManyToManyField(blank=True, to='recipe.Category'),
        ),
    ]
