# Generated by Django 3.1.4 on 2021-11-14 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0013_auto_20211113_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='stream',
            name='private_key',
            field=models.CharField(blank=True, max_length=22, null=True),
        ),
    ]
